# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/aminhb/PycharmProjects/MinimalSensGUI_v1/MinimalSensGUI_v1.07/mainWindowGUI_v1.07.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(670, 644)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(670, 644))
        MainWindow.setMaximumSize(QtCore.QSize(670, 644))
        MainWindow.setMouseTracking(True)
        MainWindow.setTabletTracking(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/minimalsens.icns"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setToolTip("")
        MainWindow.setAutoFillBackground(True)
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(True)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(671, 671))
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(5, 5, 661, 531))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(1, 1, 2, 1)
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setVerticalSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.label_NS = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_NS.setFont(font)
        self.label_NS.setObjectName("label_NoStps")
        self.gridLayout.addWidget(self.label_NS, 3, 4, 1, 4)
        self.textBrowser = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textBrowser.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textBrowser.setFont(font)
        self.textBrowser.setAutoFillBackground(True)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 20, 0, 9, 3)
        self.lineEdit_SampQT = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_SampQT.setDisabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_SampQT.setFont(font)
        self.lineEdit_SampQT.setAutoFillBackground(True)
        self.lineEdit_SampQT.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_SampQT.setObjectName("lineEdit_SampQuietTime")
        self.gridLayout.addWidget(self.lineEdit_SampQT, 10, 8, 1, 1)
        self.lineEdit_SI = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_SI.setFont(font)
        self.lineEdit_SI.setAutoFillBackground(True)
        self.lineEdit_SI.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_SI.setObjectName("lineEdit_SampleIntrvl")
        self.gridLayout.addWidget(self.lineEdit_SI, 5, 8, 1, 1)
        self.checkBox_DataSmt = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_DataSmt.setFont(font)
        self.checkBox_DataSmt.setObjectName("checkBox_DataSmth")
        self.gridLayout.addWidget(self.checkBox_DataSmt, 21, 4, 1, 5)
        self.label_adcGn = QtWidgets.QLabel(self.layoutWidget)
        self.label_adcGn.setDisabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_adcGn.setFont(font)
        self.label_adcGn.setObjectName("label_adcG")
        self.gridLayout.addWidget(self.label_adcGn, 24, 4, 1, 4)
        self.label_EChemQT = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_EChemQT.setFont(font)
        self.label_EChemQT.setObjectName("label_EChemQuietT")
        self.gridLayout.addWidget(self.label_EChemQT, 6, 4, 1, 4)
        self.label_adcSpd = QtWidgets.QLabel(self.layoutWidget)
        self.label_adcSpd.setDisabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_adcSpd.setFont(font)
        self.label_adcSpd.setObjectName("label_adcS")
        self.gridLayout.addWidget(self.label_adcSpd, 25, 4, 1, 4)
        self.label_DataSet = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_DataSet.setFont(font)
        self.label_DataSet.setObjectName("label_DataSet")
        self.label_DataSet.setStyleSheet('color: green')
        self.gridLayout.addWidget(self.label_DataSet, 20, 4, 1, 5)
        self.label_EChemSet = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_EChemSet.setFont(font)
        self.label_EChemSet.setObjectName("label_EChemSet")
        self.label_EChemSet.setStyleSheet('color: green')
        self.gridLayout.addWidget(self.label_EChemSet, 0, 4, 1, 5)
        self.graphicsView = GraphicsWindow()
        self.graphicsView.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMouseTracking(True)
        self.graphicsView.setTabletTracking(True)
        self.graphicsView.setAutoFillBackground(True)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView.setForegroundBrush(brush)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 18, 3)
        self.lineEdit_NC = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_NC.setFont(font)
        self.lineEdit_NC.setAutoFillBackground(True)
        self.lineEdit_NC.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_NC.setObjectName("lineEdit_NoStepCycles")
        self.gridLayout.addWidget(self.lineEdit_NC, 3, 8, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 26, 4, 1, 5)
        self.checkBox_SigAmp = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_SigAmp.setFont(font)
        self.checkBox_SigAmp.setObjectName("checkBox_SigAmp")
        self.gridLayout.addWidget(self.checkBox_SigAmp, 23, 4, 1, 5)
        self.lineEdit_PmV = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_PmV.setDisabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_PmV.setFont(font)
        self.lineEdit_PmV.setAutoFillBackground(True)
        self.lineEdit_PmV.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PmV.setObjectName("lineEdit_PMV")
        self.gridLayout.addWidget(self.lineEdit_PmV, 17, 8, 1, 1)
        self.checkBox_PmMod = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_PmMod.setFont(font)
        self.checkBox_PmMod.setObjectName("checkBox_PMMod")
        self.gridLayout.addWidget(self.checkBox_PmMod, 16, 4, 1, 5)
        self.RunButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.RunButton.setFont(font)
        self.RunButton.setAutoFillBackground(True)
        self.RunButton.setAutoDefault(False)
        self.RunButton.setFlat(False)
        self.RunButton.setObjectName("RunButton")
        self.gridLayout.addWidget(self.RunButton, 27, 4, 1, 4)
        self.lineEdit_SampNumbr = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_SampNumbr.setDisabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_SampNumbr.setFont(font)
        self.lineEdit_SampNumbr.setAutoFillBackground(True)
        self.lineEdit_SampNumbr.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_SampNumbr.setObjectName("lineEdit_NumbSamps")
        self.gridLayout.addWidget(self.lineEdit_SampNumbr, 11, 8, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.layoutWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 19, 4, 1, 5)
        self.lineEdit_PW = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_PW.setFont(font)
        self.lineEdit_PW.setAutoFillBackground(True)
        self.lineEdit_PW.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_PW.setObjectName("lineEdit_PulseWidth")
        self.gridLayout.addWidget(self.lineEdit_PW, 4, 8, 1, 1)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 7, 4, 1, 5)
        self.TestButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.TestButton.setFont(font)
        self.TestButton.setAutoFillBackground(True)
        self.TestButton.setObjectName("TestButton")
        self.gridLayout.addWidget(self.TestButton, 27, 8, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 19, 0, 1, 3)
        self.lineEdit_EChemQT = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_EChemQT.setFont(font)
        self.lineEdit_EChemQT.setAutoFillBackground(True)
        self.lineEdit_EChemQT.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_EChemQT.setObjectName("lineEdit_QuietTime")
        self.gridLayout.addWidget(self.lineEdit_EChemQT, 6, 8, 1, 1)
        self.label_PhotoDetMod = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_PhotoDetMod.setFont(font)
        self.label_PhotoDetMod.setObjectName("label_PhotoDetMod")
        self.label_PhotoDetMod.setStyleSheet('color: green')
        self.gridLayout.addWidget(self.label_PhotoDetMod, 15, 4, 1, 5)
        self.label_SampT = QtWidgets.QLabel(self.layoutWidget)
        self.label_SampT.setDisabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_SampT.setFont(font)
        self.label_SampT.setObjectName("label_SampT")
        self.gridLayout.addWidget(self.label_SampT, 12, 4, 1, 4)
        self.label_Vltg = QtWidgets.QLabel(self.layoutWidget)
        self.label_Vltg.setDisabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_Vltg.setFont(font)
        self.label_Vltg.setObjectName("label_Vltg")
        self.gridLayout.addWidget(self.label_Vltg, 17, 4, 1, 4)
        self.label_SamSet = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_SamSet.setFont(font)
        self.label_SamSet.setObjectName("label_SamSet")
        self.label_SamSet.setStyleSheet('color: green')
        self.gridLayout.addWidget(self.label_SamSet, 8, 4, 1, 5)
        self.label_IncubT = QtWidgets.QLabel(self.layoutWidget)
        self.label_IncubT.setDisabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_IncubT.setFont(font)
        self.label_IncubT.setObjectName("label_IncubT")
        self.gridLayout.addWidget(self.label_IncubT, 14, 4, 1, 4)
        self.lineEdit_FP = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_FP.setFont(font)
        self.lineEdit_FP.setAutoFillBackground(True)
        self.lineEdit_FP.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_FP.setObjectName("lineEdit_FinalE")
        self.gridLayout.addWidget(self.lineEdit_FP, 2, 8, 1, 1)
        self.label_IP = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_IP.setFont(font)
        self.label_IP.setObjectName("label_IP")
        self.gridLayout.addWidget(self.label_IP, 1, 4, 1, 4)
        self.label_FP = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_FP.setFont(font)
        self.label_FP.setObjectName("label_FP")
        self.gridLayout.addWidget(self.label_FP, 2, 4, 1, 4)
        self.lineEdit_IncubT = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_IncubT.setDisabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_IncubT.setFont(font)
        self.lineEdit_IncubT.setAutoFillBackground(True)
        self.lineEdit_IncubT.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_IncubT.setObjectName("lineEdit_IncubTime")
        self.gridLayout.addWidget(self.lineEdit_IncubT, 14, 8, 1, 1)
        self.comboBox_ordrs = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_ordrs.setDisabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_ordrs.setFont(font)
        self.comboBox_ordrs.setObjectName("comboBox_orders")
        self.comboBox_ordrs.addItem("")
        self.comboBox_ordrs.addItem("")
        self.comboBox_ordrs.addItem("")
        self.comboBox_ordrs.addItem("")
        self.comboBox_ordrs.addItem("")
        self.comboBox_ordrs.addItem("")
        self.comboBox_ordrs.addItem("")
        self.comboBox_ordrs.addItem("")
        self.comboBox_ordrs.addItem("")
        self.comboBox_ordrs.addItem("")
        self.comboBox_ordrs.setStyleSheet("fusion")
        self.gridLayout.addWidget(self.comboBox_ordrs, 22, 8, 1, 1)
        self.label_SampNumbr = QtWidgets.QLabel(self.layoutWidget)
        self.label_SampNumbr.setDisabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_SampNumbr.setFont(font)
        self.label_SampNumbr.setObjectName("label_NoSamp")
        self.gridLayout.addWidget(self.label_SampNumbr, 11, 4, 1, 4)
        self.label_PW = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_PW.setFont(font)
        self.label_PW.setObjectName("label_PW")
        self.gridLayout.addWidget(self.label_PW, 4, 4, 1, 4)
        self.checkBox_SampMod = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_SampMod.setFont(font)
        self.checkBox_SampMod.setObjectName("checkBox_SampMod")
        self.gridLayout.addWidget(self.checkBox_SampMod, 9, 4, 1, 5)
        self.label_SI = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_SI.setFont(font)
        self.label_SI.setObjectName("label_SI")
        self.gridLayout.addWidget(self.label_SI, 5, 4, 1, 4)
        self.lineEdit_adcSpd = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_adcSpd.setDisabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_adcSpd.setFont(font)
        self.lineEdit_adcSpd.setAutoFillBackground(True)
        self.lineEdit_adcSpd.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_adcSpd.setObjectName("lineEdit_ADCSpd")
        self.gridLayout.addWidget(self.lineEdit_adcSpd, 25, 8, 1, 1)
        self.lineEdit_adcGn = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_adcGn.setDisabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_adcGn.setFont(font)
        self.lineEdit_adcGn.setAutoFillBackground(True)
        self.lineEdit_adcGn.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_adcGn.setObjectName("lineEdit_ADCGain")
        self.gridLayout.addWidget(self.lineEdit_adcGn, 24, 8, 1, 1)
        self.label_SampQT = QtWidgets.QLabel(self.layoutWidget)
        self.label_SampQT.setDisabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_SampQT.setFont(font)
        self.label_SampQT.setObjectName("label_SampQuietT")
        self.gridLayout.addWidget(self.label_SampQT, 10, 4, 1, 4)
        self.lineEdit_SampT = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_SampT.setDisabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_SampT.setFont(font)
        self.lineEdit_SampT.setAutoFillBackground(True)
        self.lineEdit_SampT.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_SampT.setObjectName("lineEdit_SampTime")
        self.gridLayout.addWidget(self.lineEdit_SampT, 12, 8, 1, 1)
        self.checkBox_IncubMod = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_IncubMod.setFont(font)
        self.checkBox_IncubMod.setObjectName("checkBox_IncubMod")
        self.gridLayout.addWidget(self.checkBox_IncubMod, 13, 4, 1, 5)
        self.lineEdit_IP = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_IP.setFont(font)
        self.lineEdit_IP.setAutoFillBackground(True)
        self.lineEdit_IP.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_IP.setObjectName("lineEdit_InitE")
        self.gridLayout.addWidget(self.lineEdit_IP, 1, 8, 1, 1)
        self.comboBox_Smt = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_Smt.setDisabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_Smt.setFont(font)
        self.comboBox_Smt.setObjectName("comboBox_Smt")
        self.comboBox_Smt.addItem("")
        self.comboBox_Smt.addItem("")
        self.comboBox_Smt.setStyleSheet("fusion")
        self.gridLayout.addWidget(self.comboBox_Smt, 22, 4, 1, 4)
        self.line_4 = QtWidgets.QFrame(self.layoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 0, 3, 29, 1)
        self.gridLayout.setColumnStretch(0, 10)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setColumnStretch(3, 1)
        self.gridLayout.setColumnStretch(4, 1)
        self.gridLayout.setColumnStretch(5, 1)
        self.gridLayout.setColumnStretch(6, 1)
        self.gridLayout.setColumnStretch(7, 1)
        self.gridLayout.setColumnStretch(8, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 670, 22))
        self.menubar.setAutoFillBackground(True)
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setTabletTracking(True)
        self.menuFile.setToolTip("")
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setTabletTracking(True)
        self.menuHelp.setToolTip("")
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setAutoFillBackground(True)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setAutoFillBackground(True)
        self.toolBar.setMovable(False)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setCheckable(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/new.icns"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon1)
        self.actionNew.setShortcutVisibleInContextMenu(True)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setEnabled(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/open.icns"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon2)
        self.actionOpen.setShortcutVisibleInContextMenu(True)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/exit.icns"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon3)
        self.actionExit.setObjectName("actionExit")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/help.icns"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon4)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout_Us = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/about.icns"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_Us.setIcon(icon5)
        self.actionAbout_Us.setObjectName("actionAbout_Us")
        self.actionBluetooth = QtWidgets.QAction(MainWindow)
        self.actionBluetooth.setCheckable(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../../.designer/MinimalSensGUI_v1.03/Icons/bluetooth.icns"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBluetooth.setIcon(icon6)
        self.actionBluetooth.setObjectName("actionBluetooth")
        self.actionUSB = QtWidgets.QAction(MainWindow)
        self.actionUSB.setCheckable(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Icons/usb.icns"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUSB.setIcon(icon7)
        self.actionUSB.setObjectName("actionUSB")
        self.actionWifi = QtWidgets.QAction(MainWindow)
        self.actionWifi.setCheckable(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Icons/wifi.icns"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionWifi.setIcon(icon8)
        self.actionWifi.setObjectName("actionWifi")
        self.actionConnection = QtWidgets.QAction(MainWindow)
        self.actionConnection.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Icons/disconnect.icns"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap(":/Icons/disconnect.icns"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon9.addPixmap(QtGui.QPixmap(":/Icons/disconnect.icns"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap(":/Icons/disconnect.icns"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon9.addPixmap(QtGui.QPixmap(":/Icons/disconnect.icns"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap(":/Icons/disconnect.icns"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.actionConnection.setIcon(icon9)
        self.actionConnection.setObjectName("actionConnection")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout_Us)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)
        self.toolBar.addSeparator()

        spacer = QtGui.QWidget(self)
        spacer.setSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        self.toolBar.addWidget(spacer)

        self.toolBar.addAction(self.actionConnection)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.graphicsView, self.textBrowser)
        MainWindow.setTabOrder(self.textBrowser, self.lineEdit_IP)
        MainWindow.setTabOrder(self.lineEdit_IP, self.lineEdit_FP)
        MainWindow.setTabOrder(self.lineEdit_FP, self.lineEdit_NC)
        MainWindow.setTabOrder(self.lineEdit_NC, self.lineEdit_PW)
        MainWindow.setTabOrder(self.lineEdit_PW, self.lineEdit_SI)
        MainWindow.setTabOrder(self.lineEdit_SI, self.lineEdit_EChemQT)
        MainWindow.setTabOrder(self.lineEdit_EChemQT, self.checkBox_SampMod)
        MainWindow.setTabOrder(self.checkBox_SampMod, self.lineEdit_SampQT)
        MainWindow.setTabOrder(self.lineEdit_SampQT, self.lineEdit_SampNumbr)
        MainWindow.setTabOrder(self.lineEdit_SampNumbr, self.lineEdit_SampT)
        MainWindow.setTabOrder(self.lineEdit_SampT, self.checkBox_IncubMod)
        MainWindow.setTabOrder(self.checkBox_IncubMod, self.lineEdit_IncubT)
        MainWindow.setTabOrder(self.lineEdit_IncubT, self.checkBox_PmMod)
        MainWindow.setTabOrder(self.checkBox_PmMod, self.lineEdit_PmV)
        MainWindow.setTabOrder(self.lineEdit_PmV, self.checkBox_DataSmt)
        MainWindow.setTabOrder(self.checkBox_DataSmt, self.comboBox_Smt)
        MainWindow.setTabOrder(self.comboBox_Smt, self.comboBox_ordrs)
        MainWindow.setTabOrder(self.comboBox_ordrs, self.checkBox_SigAmp)
        MainWindow.setTabOrder(self.checkBox_SigAmp, self.lineEdit_adcGn)
        MainWindow.setTabOrder(self.lineEdit_adcGn, self.label_adcSpd)
        MainWindow.setTabOrder(self.label_adcSpd, self.RunButton)
        MainWindow.setTabOrder(self.RunButton, self.TestButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MinimalSens"))
        MainWindow.setWhatsThis(_translate("MainWindow", "MinimalSens"))
        self.label_NS.setToolTip(_translate("MainWindow", "Number of Steps"))
        self.label_NS.setStatusTip(_translate("MainWindow", "Number of step potentials"))
        self.label_NS.setWhatsThis(_translate("MainWindow", "Number of step potentials"))
        self.label_NS.setText(_translate("MainWindow", "Number of Cycles"))
        self.textBrowser.setToolTip(_translate("MainWindow", "Status Window"))
        self.textBrowser.setStatusTip(_translate("MainWindow", "Outputs will be shown here - follow the instructions here"))
        self.textBrowser.setWhatsThis(_translate("MainWindow", "Status Window"))
        self.lineEdit_SampQT.setToolTip(_translate("MainWindow", "Sample Quiet Time"))
        self.lineEdit_SampQT.setStatusTip(_translate("MainWindow", "Sampling quiet time in seconds"))
        self.lineEdit_SampQT.setWhatsThis(_translate("MainWindow", "Sampling quiet time"))
        self.lineEdit_SampQT.setText(_translate("MainWindow", "0.1"))
        self.lineEdit_SI.setToolTip(_translate("MainWindow", "Sample Interval"))
        self.lineEdit_SI.setStatusTip(_translate("MainWindow", "Input the sampling intervals in here"))
        self.lineEdit_SI.setWhatsThis(_translate("MainWindow", "Sampling intervals in seconds"))
        self.lineEdit_SI.setText(_translate("MainWindow", "0.1"))
        self.checkBox_DataSmt.setToolTip(_translate("MainWindow", "Data"))
        self.checkBox_DataSmt.setStatusTip(_translate("MainWindow", "Data Smooting Activation"))
        self.checkBox_DataSmt.setWhatsThis(_translate("MainWindow", "Check to activate the smoothing algorithm"))
        self.checkBox_DataSmt.setText(_translate("MainWindow", "Data Smooth"))
        self.label_adcGn.setToolTip(_translate("MainWindow", "ADC Gain"))
        self.label_adcGn.setStatusTip(_translate("MainWindow", "Analog-to-Digital converter gain"))
        self.label_adcGn.setWhatsThis(_translate("MainWindow", "Analog-to-Digital converter gain"))
        self.label_adcGn.setText(_translate("MainWindow", "ADC Gain"))
        self.label_EChemQT.setToolTip(_translate("MainWindow", "Quiet Time"))
        self.label_EChemQT.setStatusTip(_translate("MainWindow", "Quiet time at the beginning of EChem experiment"))
        self.label_EChemQT.setWhatsThis(_translate("MainWindow", "Quiet time"))
        self.label_EChemQT.setText(_translate("MainWindow", "EChem Quiet Time (s)"))
        self.label_adcSpd.setToolTip(_translate("MainWindow", "ADC Speed"))
        self.label_adcSpd.setStatusTip(_translate("MainWindow", "Analog-to-Digital converter speed"))
        self.label_adcSpd.setWhatsThis(_translate("MainWindow", "Analog-to-Digital converter speed"))
        self.label_adcSpd.setText(_translate("MainWindow", "ADC Speed"))
        self.label_DataSet.setToolTip(_translate("MainWindow", "Data Processing "))
        self.label_DataSet.setStatusTip(_translate("MainWindow", "Data Processing "))
        self.label_DataSet.setWhatsThis(_translate("MainWindow", "Data Processing "))
        self.label_DataSet.setText(_translate("MainWindow", "Data Processing."))
        self.label_EChemSet.setToolTip(_translate("MainWindow", "Electrochemical Settings"))
        self.label_EChemSet.setStatusTip(_translate("MainWindow", "Electrochemical Settings"))
        self.label_EChemSet.setWhatsThis(_translate("MainWindow", "Electrochemical Settings"))
        self.label_EChemSet.setText(_translate("MainWindow", "ECL Settings."))
        self.graphicsView.setToolTip(_translate("MainWindow", "Graphing Window"))
        self.graphicsView.setStatusTip(_translate("MainWindow", "Output graphs will be shown here"))
        self.graphicsView.setWhatsThis(_translate("MainWindow", "Graphing Window"))
        self.lineEdit_NC.setToolTip(_translate("MainWindow", "Number of Steps"))
        self.lineEdit_NC.setStatusTip(_translate("MainWindow", "Input the number of the step-potentials here"))
        self.lineEdit_NC.setWhatsThis(_translate("MainWindow", "Number of step-potentials"))
        self.lineEdit_NC.setText(_translate("MainWindow", "1"))
        self.checkBox_SigAmp.setToolTip(_translate("MainWindow", "Signal Amplification"))
        self.checkBox_SigAmp.setStatusTip(_translate("MainWindow", "Signal Amplification"))
        self.checkBox_SigAmp.setWhatsThis(_translate("MainWindow", "Signal Amplification"))
        self.checkBox_SigAmp.setText(_translate("MainWindow", "Signal Amplification"))
        self.lineEdit_PmV.setToolTip(_translate("MainWindow", "PMT Voltage"))
        self.lineEdit_PmV.setStatusTip(_translate("MainWindow", "Input the HV in here (200-900V)"))
        self.lineEdit_PmV.setWhatsThis(_translate("MainWindow", "High-volage adjustments (200-900V)"))
        self.lineEdit_PmV.setText(_translate("MainWindow", "200"))
        self.checkBox_PmMod.setToolTip(_translate("MainWindow", "Photomultiplyer Activation"))
        self.checkBox_PmMod.setStatusTip(_translate("MainWindow", "Photomultiplyer Activation"))
        self.checkBox_PmMod.setWhatsThis(_translate("MainWindow", "Check to activate the photomultiplyer module"))
        self.checkBox_PmMod.setText(_translate("MainWindow", "Photomultiplyer Module"))
        self.RunButton.setToolTip(_translate("MainWindow", "Run"))
        self.RunButton.setStatusTip(_translate("MainWindow", "Click to initiate the experiment"))
        self.RunButton.setWhatsThis(_translate("MainWindow", "Initiates the experiment"))
        self.RunButton.setText(_translate("MainWindow", "Run"))
        self.lineEdit_SampNumbr.setToolTip(_translate("MainWindow", "Samples"))
        self.lineEdit_SampNumbr.setStatusTip(_translate("MainWindow", "Input number of samples in here"))
        self.lineEdit_SampNumbr.setWhatsThis(_translate("MainWindow", "Input number of samples in here"))
        self.lineEdit_SampNumbr.setText(_translate("MainWindow", "1"))
        self.lineEdit_PW.setToolTip(_translate("MainWindow", "Pulse Width"))
        self.lineEdit_PW.setStatusTip(_translate("MainWindow", "Input the length of the pulse width here"))
        self.lineEdit_PW.setWhatsThis(_translate("MainWindow", "Pulse width length in seconds"))
        self.lineEdit_PW.setText(_translate("MainWindow", "1"))
        self.TestButton.setToolTip(_translate("MainWindow", "Test"))
        self.TestButton.setStatusTip(_translate("MainWindow", "Test Button"))
        self.TestButton.setWhatsThis(_translate("MainWindow", "Test Button"))
        self.TestButton.setText(_translate("MainWindow", "Test"))
        self.lineEdit_EChemQT.setToolTip(_translate("MainWindow", "Quiet Time"))
        self.lineEdit_EChemQT.setStatusTip(_translate("MainWindow", "Quiet time at the begining of the experiment"))
        self.lineEdit_EChemQT.setWhatsThis(_translate("MainWindow", "Quiet time"))
        self.lineEdit_EChemQT.setText(_translate("MainWindow", "1"))
        self.label_PhotoDetMod.setToolTip(_translate("MainWindow", "Photodetection Module"))
        self.label_PhotoDetMod.setStatusTip(_translate("MainWindow", "Photodetection Module"))
        self.label_PhotoDetMod.setWhatsThis(_translate("MainWindow", "Photodetection Module"))
        self.label_PhotoDetMod.setText(_translate("MainWindow", "Photodetection Module."))
        self.label_SampT.setToolTip(_translate("MainWindow", "Sampling Time"))
        self.label_SampT.setStatusTip(_translate("MainWindow", "Sampling Time"))
        self.label_SampT.setWhatsThis(_translate("MainWindow", "Sampling Time"))
        self.label_SampT.setText(_translate("MainWindow", "Sampling Time (s)"))
        self.label_Vltg.setStatusTip(_translate("MainWindow", "High-volage adjustments (200-900V)"))
        self.label_Vltg.setWhatsThis(_translate("MainWindow", "High-volage adjustments (200-900V)"))
        self.label_Vltg.setText(_translate("MainWindow", "Voltage (V)"))
        self.label_SamSet.setToolTip(_translate("MainWindow", "Sampling Settings"))
        self.label_SamSet.setStatusTip(_translate("MainWindow", "Sampling Settings"))
        self.label_SamSet.setWhatsThis(_translate("MainWindow", "Sampling Settings"))
        self.label_SamSet.setText(_translate("MainWindow", "Sampling Settings."))
        self.label_IncubT.setToolTip(_translate("MainWindow", "Incubation Time"))
        self.label_IncubT.setStatusTip(_translate("MainWindow", "Incubation time in minutes"))
        self.label_IncubT.setWhatsThis(_translate("MainWindow", "Incubation time in minutes"))
        self.label_IncubT.setText(_translate("MainWindow", "Incubation Time (min)"))
        self.lineEdit_FP.setToolTip(_translate("MainWindow", "Final Potential"))
        self.lineEdit_FP.setStatusTip(_translate("MainWindow", "Input the final potential here"))
        self.lineEdit_FP.setWhatsThis(_translate("MainWindow", "Final Potential"))
        self.lineEdit_FP.setText(_translate("MainWindow", "0.0"))
        self.label_IP.setToolTip(_translate("MainWindow", "Initial Potential"))
        self.label_IP.setStatusTip(_translate("MainWindow", "Initial Potential"))
        self.label_IP.setWhatsThis(_translate("MainWindow", "Initial Potential"))
        self.label_IP.setText(_translate("MainWindow", "Initial Potential (V)"))
        self.label_FP.setToolTip(_translate("MainWindow", "Final Potential"))
        self.label_FP.setStatusTip(_translate("MainWindow", "Final Potential"))
        self.label_FP.setWhatsThis(_translate("MainWindow", "Final Potential"))
        self.label_FP.setText(_translate("MainWindow", "Final Potential (V)"))
        self.lineEdit_IncubT.setToolTip(_translate("MainWindow", "Incubation Time"))
        self.lineEdit_IncubT.setStatusTip(_translate("MainWindow", "Incubation Time"))
        self.lineEdit_IncubT.setWhatsThis(_translate("MainWindow", "Input the incubation time in here"))
        self.lineEdit_IncubT.setText(_translate("MainWindow", "1"))
        self.comboBox_ordrs.setToolTip(_translate("MainWindow", "Algorithm order"))
        self.comboBox_ordrs.setStatusTip(_translate("MainWindow", "Choose the order of the algorithm"))
        self.comboBox_ordrs.setWhatsThis(_translate("MainWindow", "Choose the order of the algorithm"))
        self.comboBox_ordrs.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_ordrs.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_ordrs.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_ordrs.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_ordrs.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_ordrs.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_ordrs.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_ordrs.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_ordrs.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_ordrs.setItemText(9, _translate("MainWindow", "10"))
        self.label_SampNumbr.setToolTip(_translate("MainWindow", "Samples"))
        self.label_SampNumbr.setStatusTip(_translate("MainWindow", "Number or Samples"))
        self.label_SampNumbr.setWhatsThis(_translate("MainWindow", "Number of Samples"))
        self.label_SampNumbr.setText(_translate("MainWindow", "Samples"))
        self.label_PW.setToolTip(_translate("MainWindow", "Pulse Width"))
        self.label_PW.setStatusTip(_translate("MainWindow", "Pulse width "))
        self.label_PW.setWhatsThis(_translate("MainWindow", "Pulse width"))
        self.label_PW.setText(_translate("MainWindow", "Pulse Width (s)"))
        self.checkBox_SampMod.setToolTip(_translate("MainWindow", "Data Smooth"))
        self.checkBox_SampMod.setStatusTip(_translate("MainWindow", "Sampling Mode Activation"))
        self.checkBox_SampMod.setWhatsThis(_translate("MainWindow", "Sampling Mode Activation"))
        self.checkBox_SampMod.setText(_translate("MainWindow", "Sampling Mode"))
        self.label_SI.setToolTip(_translate("MainWindow", "Sample Interval"))
        self.label_SI.setStatusTip(_translate("MainWindow", "Sampling intervals"))
        self.label_SI.setWhatsThis(_translate("MainWindow", "Sampling intervals"))
        self.label_SI.setText(_translate("MainWindow", "Sampling Intervals (s)"))
        self.lineEdit_adcSpd.setToolTip(_translate("MainWindow", "ADC Speed"))
        self.lineEdit_adcSpd.setStatusTip(_translate("MainWindow", "Input the ADC speed here (1 or 2)"))
        self.lineEdit_adcSpd.setWhatsThis(_translate("MainWindow", "Analog-to-Digital converter speed"))
        self.lineEdit_adcSpd.setText(_translate("MainWindow", "1"))
        self.lineEdit_adcGn.setToolTip(_translate("MainWindow", "ADC Gain"))
        self.lineEdit_adcGn.setStatusTip(_translate("MainWindow", "Input the ADC gain here (1, 2, 64 or 128)"))
        self.lineEdit_adcGn.setWhatsThis(_translate("MainWindow", "Analog-to-Digital converter gain"))
        self.lineEdit_adcGn.setText(_translate("MainWindow", "1"))
        self.label_SampQT.setToolTip(_translate("MainWindow", "Sample Quiet Time"))
        self.label_SampQT.setStatusTip(_translate("MainWindow", "Sample Quiet Time"))
        self.label_SampQT.setWhatsThis(_translate("MainWindow", "Sample Quiet Time"))
        self.label_SampQT.setText(_translate("MainWindow", "Sampler Quiet Time (s)"))
        self.lineEdit_SampT.setToolTip(_translate("MainWindow", "Sampling Time"))
        self.lineEdit_SampT.setStatusTip(_translate("MainWindow", "Sampling Time"))
        self.lineEdit_SampT.setWhatsThis(_translate("MainWindow", "Inpu the sampling time duration in here"))
        self.lineEdit_SampT.setText(_translate("MainWindow", "1"))
        self.checkBox_IncubMod.setToolTip(_translate("MainWindow", "Incubation Mode Activation"))
        self.checkBox_IncubMod.setStatusTip(_translate("MainWindow", "Incubation Mode Activation"))
        self.checkBox_IncubMod.setWhatsThis(_translate("MainWindow", "Check to activate the Incubation Mode "))
        self.checkBox_IncubMod.setText(_translate("MainWindow", "Incubation Mode"))
        self.lineEdit_IP.setToolTip(_translate("MainWindow", "Initial Potential"))
        self.lineEdit_IP.setStatusTip(_translate("MainWindow", "Input the initial potential here"))
        self.lineEdit_IP.setWhatsThis(_translate("MainWindow", "Initial Potential"))
        self.lineEdit_IP.setText(_translate("MainWindow", "0.0"))
        self.comboBox_Smt.setToolTip(_translate("MainWindow", "Smoothing Algorithm"))
        self.comboBox_Smt.setStatusTip(_translate("MainWindow", "Choose your smoothin algorithm here"))
        self.comboBox_Smt.setWhatsThis(_translate("MainWindow", "Smoothing Algorithm"))
        self.comboBox_Smt.setItemText(0, _translate("MainWindow", "Savitzky-Golay"))
        self.comboBox_Smt.setItemText(1, _translate("MainWindow", "Trianagular Moving Ave."))
        self.menuFile.setStatusTip(_translate("MainWindow", "File Tab"))
        self.menuFile.setWhatsThis(_translate("MainWindow", "File Tab"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setStatusTip(_translate("MainWindow", "Help Tab"))
        self.menuHelp.setWhatsThis(_translate("MainWindow", "Help Tab"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.statusbar.setToolTip(_translate("MainWindow", "Staus Bar"))
        self.statusbar.setStatusTip(_translate("MainWindow", "Status Bar"))
        self.statusbar.setWhatsThis(_translate("MainWindow", "Status Bar"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setToolTip(_translate("MainWindow", "Click to create a new file"))
        self.actionNew.setStatusTip(_translate("MainWindow", "Create a new file "))
        self.actionNew.setWhatsThis(_translate("MainWindow", "New File"))
        self.actionNew.setShortcut(_translate("MainWindow", "Meta+N"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setToolTip(_translate("MainWindow", "Click to open a file"))
        self.actionOpen.setStatusTip(_translate("MainWindow", "Open a file"))
        self.actionOpen.setWhatsThis(_translate("MainWindow", "Open file"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Meta+O"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setToolTip(_translate("MainWindow", "Click here to exit"))
        self.actionExit.setStatusTip(_translate("MainWindow", "Exit the program"))
        self.actionExit.setWhatsThis(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Meta+Z"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionHelp.setToolTip(_translate("MainWindow", "Click here for help"))
        self.actionHelp.setStatusTip(_translate("MainWindow", "Help ?"))
        self.actionHelp.setWhatsThis(_translate("MainWindow", "Help"))
        self.actionHelp.setShortcut(_translate("MainWindow", "F1"))
        self.actionAbout_Us.setText(_translate("MainWindow", "About Us"))
        self.actionAbout_Us.setStatusTip(_translate("MainWindow", "About"))
        self.actionAbout_Us.setWhatsThis(_translate("MainWindow", "About Us"))
        self.actionAbout_Us.setShortcut(_translate("MainWindow", "F12"))
        self.actionBluetooth.setText(_translate("MainWindow", "Bluetooth"))
        self.actionBluetooth.setToolTip(_translate("MainWindow", "Click to connect via Bluetooth"))
        self.actionBluetooth.setShortcut(_translate("MainWindow", "Meta+B"))
        self.actionUSB.setText(_translate("MainWindow", "USB"))
        self.actionUSB.setToolTip(_translate("MainWindow", "Click to connect via USB"))
        self.actionUSB.setShortcut(_translate("MainWindow", "Meta+U"))
        self.actionWifi.setText(_translate("MainWindow", "Wifi"))
        self.actionWifi.setToolTip(_translate("MainWindow", "Click to connect via Wifi"))
        self.actionWifi.setShortcut(_translate("MainWindow", "Meta+W"))
        self.actionConnection.setText(_translate("MainWindow", "Connection"))
        self.actionConnection.setToolTip(_translate("MainWindow", "Click to connect"))
        self.actionConnection.setStatusTip(_translate("MainWindow", "Click to connect"))
        self.actionConnection.setShortcut(_translate("MainWindow", "Meta+C"))

from pyqtgraph import GraphicsWindow
import icons_rc
